### ISSUE TITLE
max_note_width not doing anything

### ISSUE THREAD

**Issue by gutestun** [obsidian-html/obsidian-html#242]
max_note_width does not alter the width of notes in documentation, nor no_tabs mode.

**Comment by dwrolvink** [comment]
yes, found this issue half an hour ago by coincidence
should be fixed in the current master branch code

I'm planning on creating a new release somewhere this weekend, should be fixed by then.

In short, there is a `.container` block in callouts.css that shouldn't be there.

**Comment by dwrolvink** [comment]
This should be fixed in version 2.2.0. Run `pip install obsidianhtml --upgrade` to fetch the newest release.

Closing this out of optimism, if it doesn't work then just post here and I'll reopen it.

**Comment by benbohmer** [comment]
Thanks for the quick reply, but sorry... bad news: Still doesn't seem to work...

**Comment by dwrolvink** [comment]
Alright, let's look into it then.

If you have the html hosted somewhere / can host it somewhere, that would help immensely.

Can you also share your config yaml? I'm mostly interested in everything under
```yaml
toggles:
```

**Comment by benbohmer** [comment]
There is only this:
`      layout: documentation  
      max_note_width: 250px`

And it's not hosted anywhere, but I just shared a repo with the output with you.

**Comment by dwrolvink** [comment]
Pretty sure that is illegal configuration, so you probably mean this?
``` yaml
toggles:
  features:
    styling: 
      layout: documentation
      max_note_width: 250px
```

note that the spaces/newlines are important. (but it should give an error if you get it wrong so you probably have configured it right).

I'll wait till I can see your code and look at that :+1:

**Comment by dwrolvink** [comment]
When running your code, I get this, the note is roughly 250px wide, so not sure what the problem is?

![image](https://user-images.githubusercontent.com/30291690/167378069-e25b8339-e41a-49a6-b024-12c932447286.png)

![image](https://user-images.githubusercontent.com/30291690/167378247-ea6812e4-3aa8-4651-847c-769d04aec374.png)

**Comment by benbohmer** [comment]
This is embarrassing, since my day-to-day job has me testing websites in different browsers and renderers.

Turns out it only not works in my main Firefox profile, where I have more extensions than is advisable to maintain an overview of them all...

Apologies for wasting your time, but thanks so much!

P.S. yes, code in my yaml is correct, just malformed in the comment.

**Comment by dwrolvink** [comment]
Haha no problem, happy it works!

I have some weird issues sometimes that no matter what I do, I cannot clear the cache in my firefox session, I have to load it in private then to see the js/css changes, so I know the feeling :+1:
